### ISSUE TITLE
当玩家退出时,监控依旧在查询此玩家的信息

### ISSUE THREAD

**Issue by Primia** [XiaoHuiHui233/MonitorR#2]
服务器MCDR后台日志：
[MCDR] [2021-08-07 09:46:58] [MonitorR/WARNING]: [Minecraft Data API] Query for player zi_xian at path  Pos timeout
[MCDR] [2021-08-07 09:47:03] [MonitorR/WARNING]: [Minecraft Data API] Query for player greenskype at path  Pos timeout
[MCDR] [2021-08-07 09:47:08] [MonitorR/WARNING]: [Minecraft Data API] Query for player YiFeng1999 at path  Pos timeout

**Comment by XiaoHuiHui233** [comment]
能给出更多信息么 比如MCDR版本、游戏版本以及使用的是哪个端？  

插件会根据MCDR的on_player_joined和on_player_left两个事件控制玩家列表。因此玩家列表不匹配是存在可能性的，目前想到的可能性有如下：  
1. MCDR的输出时序不一致，同时又有玩家频繁进退，导致on_player_left事件先于on_player_joined触发  
2. 服务端非正常退出（如卡死，被kill等），但是MCDR没有退出，继续运行服务。
这通常会出现在服务器有非MCDR触发的重启保护的情况，遇到服务器挂掉会自动重启。按理说服务器重启是可以触发on_server_stop事件的，我在该事件里重置了玩家列表，因此只要是MCDR可控的情况，应该不会出现这个问题的。  

还有一些其他可能的非预期情况，但是我没法有效的判断，需要提供更多的信息，希望您可以提供更详细的情况介绍，方便我追踪错误的来源，非常感谢您的反馈。

**Comment by Primia** [comment]
游戏版本Fabric 1.16.5  DataApi 1.3
可能是由于disablejoinleavemessage-1.0.1.jar这个mod造成的，因为服务器是BC群组服，我需要关闭子服的进出消息。
当玩家退出时，服务器后台是这样的：
[00:00:45] [Server thread/INFO]: BragMatthew lost connection: Disconnected
[00:00:45] [Server thread/INFO]: Canceling message "BragMatthew left the game"
当玩家进入时，服务器后台是这样的：
[00:18:53] [Server thread/INFO]: BragMatthew logged in with entity id 1707068 at (0.7593377752349042, 67.0, -772.8327876572727)
[00:18:53] [Server thread/INFO]: Canceling message "BragMatthew joined the game"
也许吧检测join改为logged、left改为lost connection会恢复正常？
这样的话也不能算是插件的bug了，应该属于其他原因影响的。给你添麻烦了=w=

**Comment by linstar-fxt** [comment]
disablejoinleavemessage这个Mod会修改玩家退出的info
这导致了MCDR无法识别info，也就导致on_player_left监听器没有被触发
确实有很多BC服需要使用disablejoinleavemessage，我在我的fork里修复了这个bug
[https://github.com/linstar-fxt/MonitorR](url)
通过检测不管什么服都有的[lost connection: Disconnected]达到on_player_left的目的
代码小白，风格和XiaoHuiHui大大差太多了:D

**Comment by XiaoHuiHui233** [comment]
了解了，我先去反馈给Fallen看看是从MCDR角度解决这个问题还是从插件的角度。如果是从插件的角度话我考虑给配置文件加个开关处理下，用这个mod就打开开关，通过判断info的信息处理left，不依赖MCDR的on_player_left事件。

**Comment by XiaoHuiHui233** [comment]
@linstar-fxt 你fork修改的不对啊 你把on_player_joined的覆盖了，但是你添加的是on_player_left的逻辑。

**Comment by XiaoHuiHui233** [comment]
我问过Fallen了，MCDR之所以不用`xxx joined the game`作为on_player_joined的判断是因为水桶端没这个提示。而他怀疑`xxx lost connection`这个消息可能被重复发送，所以不用它作为on_player_left的判断。如果可以在多个端测试确定`xxx lost connection`这个消息会被唯一触发的话，他是同意从MCDR的角度解决这个问题的。如果MCDR会解决这个问题，那插件就不考虑解决了。

**Comment by linstar-fxt** [comment]
好家伙，我在github上改错了，本地测试的是改对的，实在不好意思（）感谢大佬答疑解惑
xxx lost connection 这个info我会在多端测试，基于原版端的服务器都是单一触发

**Comment by XiaoHuiHui233** [comment]
@linstar-fxt 你在MCDR的讨论群里吗？如果在的话你可以做测试然后直接给Fallen说结果。

如果你要测试的话，需要理解MCDR工作的原理，实际上几个事件的触发都是写在Handler里的，以[VanillaHandler](https://github.com/Fallen-Breath/MCDReforged/blob/master/mcdreforged/handler/impl/vanilla_handler.py)为例，见49行的`on_player_left`函数，就是实现玩家离开的触发。

按照Fallen的意思，他不想单独为这个mod做特例，相反他更想作为一个端来做特例，或者说是新实现一类Handler。不过测试不用那么复杂，你可以看到在几个不同的Handler里都有`on_player_left`的实现，你只需要把原来用`xxx left the game`的实现都改为`xxx lost connection`的判断就行，之后在这几个修改过的Handler对应的端上测试，确保在一些极端的网络条件下（比如频繁重连）不会出现一致性问题。

我建议可以在MCDR的issue里开一个新的说明一下这个问题，并且持续跟进。

**Comment by linstar-fxt** [comment]
可以，谢谢大佬指点
