### ISSUE TITLE
MCDR 2兼容

### ISSUE THREAD

**Issue by Glucy-2** [XiaoHuiHui233/MonitorR#3]
插件在MCDR 2用不了了

**Comment by goolured** [comment]
> 插件在MCDR 2用不了了

作者没做支持

**Comment by XiaoHuiHui233** [comment]
最新的commit已经提供了V2兼容的形式，但依旧是V1的单文件插件形式。

从使用角度来说，V2的兼容性目前没有问题。
至于使用多文件插件形式重构整个插件在计划中，但没有预期时间。
